### ISSUE TITLE
Non translated string

### ISSUE THREAD

**Issue by ahouin** [pancakeapp/translations#76] opened 2015-09-04 15:25 UTC
Here's a non translated string in the archived credit notes section.

![pancake](https://cloud.githubusercontent.com/assets/1697415/9687474/ac623f44-52f7-11e5-86e4-0cd83d15746d.jpg)

**Comment by ahouin** [comment] 2015-09-10 12:36
Here's some more

![pancake](https://cloud.githubusercontent.com/assets/1697415/9788331/01674ffe-5797-11e5-8cab-884cde448a01.jpg)

**Comment by ahouin** [comment] 2015-09-10 12:38
Here's some more. The underlined words should be in singular form instead of plurial.

![pancake](https://cloud.githubusercontent.com/assets/1697415/9788375/5706eb2c-5797-11e5-88c4-eb03ce4a0577.jpg)

**Comment by BrunoDeBarros** [comment] 2015-09-10 20:44
@ahouin I think there's something going wrong with your Pancake installation. Here's what I see:

<img width="684" alt="screen shot 2015-09-10 at 21 43 29" src="https://cloud.githubusercontent.com/assets/5393/9800461/04b9ded8-5805-11e5-9a62-efd7e7360302.png">

<img width="330" alt="screen shot 2015-09-10 at 21 43 52" src="https://cloud.githubusercontent.com/assets/5393/9800483/1f70241c-5805-11e5-839b-f3b255b528b1.png">

**Comment by BrunoDeBarros** [comment] 2015-09-10 20:45
If there's a problem with your installations, could you check if you're on Pancake 4.8.39? If you are, can you go to Settings > Errors & Diagnostics and use the scanner? See what it tells you. If you can't update or the scanner shows you have modified files, check this out: https://www.pancakeapp.com/faq/manual-update

**Comment by ahouin** [comment] 2015-09-13 01:42
I'm on v4.8.40 right now and I used the scanner. 

Il semble y avoir un problème avec vos fichiers Pancake.

287 fichiers ont été modifiés:
system/pancake/config/config.php
system/pancake/migrations/213_Add_reusable_items_taxes.php
system/pancake/modules/settings/models/key_m.php
third_party/themes/admin/pancake/fonts/svgs/fi-address-book.svg
third_party/themes/admin/pancake/fonts/svgs/fi-alert.svg
third_party/themes/admin/pancake/fonts/svgs/fi-align-center.svg
third_party/themes/admin/pancake/fonts/svgs/fi-align-justify.svg
third_party/themes/admin/pancake/fonts/svgs/fi-align-left.svg
third_party/themes/admin/pancake/fonts/svgs/fi-align-right.svg
third_party/themes/admin/pancake/fonts/svgs/fi-anchor.svg
... et 277 autre.

I've never did anything to these files. I don't know what's happening.

**Comment by BrunoDeBarros** [comment] 2015-09-14 18:57
@ahouin That looks like it might've been caused by uploading using FTP's ASCII mode. It used to do that to me as well when I uploaded Pancake files, until I forced everything to be uploaded in binary mode. I can help you out with that. Start a ticket, so we can talk about it privately? https://www.pancakeapp.com/account/support/ticket/new

**Comment by ahouin** [comment] 2015-09-17 12:51
I've opened a ticket about this. I'm awaiting your answer. I reuploaded by FTP my Pancake installation in binary mode and it didn't change a thing.

**Comment by BrunoDeBarros** [comment] 2015-09-20 00:07
I've replied to you there. I'm closing this issue as it doesn't seem to be an issue with Pancake's translations.

**Closed by BrunoDeBarros** 2015-09-20 00:07 UTC
